specVersion: 0.0.1
description: SugarFunge SubQL
repository: https://github.com/SugarFunge/sf-subql.git
schema: ./schema.graphql
network:
  endpoint: ws://127.0.0.1:9944
  dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
